name: Reusable Workflow

on:
  workflow_call:
    inputs:
      stack_env:
        description: 'The environment to deploy to'
        required: true
        type: string
        default: 'dev'
      dummy_parameter:
        description: 'A dummy parameter for testing'
        required: false
        type: string
        default: 'default-value'

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo dummy parameter
        run: |
          echo "Received dummy parameter: ${{ inputs.dummy_parameter }}"