name: Sub workflow

on:
  workflow_call:
    inputs:
      stack_env:
        description: 'The environment to deploy to'
        required: true
        type: string
        default: 'dev'
      another_parameter:
        description: 'Another parameter for testing'
        required: false
        type: string
        default: 'another-default-value'
    secrets:
      FOOBAR:
        description: 'A secret parameter for testing'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.stack_env }}_deploy
    steps:
      - name: Echo another parameter
        run: |
          echo "Received another parameter: ${{ inputs.another_parameter }}"
      - name: Check secret
        env:
          FOOBAR: ${{ secrets.FOOBAR }}
        if: ${{ env.FOOBAR != '' }}
        run: |
          echo "FOOBAR secret is set."