name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Building..."
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "Testing..."
  pulumi:
    needs: test
    strategy:
      matrix:
        stack_env: [ dev, qa, prod ]
    uses: ./.github/workflows/_foo-preview.yml
    with:
      stack_env: ${{ matrix.stack_env }}
      dummy_parameter: 'test-value-from-main-workflow'
