name: Main Workflow

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  trigger-reusable:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      dummy_parameter: 'test-value-from-main-workflow'
