name: Reusable Workflow

on:
  workflow_call:
    inputs:
      dummy_parameter:
        description: 'A dummy parameter for testing'
        required: false
        type: string
        default: 'default-value'

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Echo dummy parameter
        run: |
          echo "Received dummy parameter: ${{ inputs.dummy_parameter }}"
